sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
addons:
  apt:
      packages:
        - libgpgme11-dev
install: pip install -e ".[dev]"
script: nosetests
